@extends('layouts.app')

@section('title', 'HerveShop — Les meilleurs produits au meilleur prix')
@section('meta_description', 'Découvrez HerveShop : électronique, mode, maison, beauté et accessoires au meilleur prix, avec livraison partout au Togo.')

@section('content')
    <section class="home-hero"><div class="hero-copy"><span class="eyebrow">Bienvenue sur HerveShop</span><h1>Les meilleurs produits<br><strong>au meilleur prix !</strong></h1><p>Découvrez une large gamme de produits de qualité : électronique, mode, maison, beauté et bien plus encore.</p><div class="hero-actions"><a href="{{ route('products.index') }}" class="home-btn home-btn-primary">Découvrir la boutique <span>→</span></a><a href="{{ route('products.index', ['tri' => 'prix_asc']) }}" class="home-btn home-btn-light">Voir les offres</a></div><div class="hero-promises"><span><x-icon name="truck"/> Livraison rapide<br><small>Partout au Togo</small></span><span><x-icon name="shield"/> Paiement sécurisé<br><small>Mobile Money & autres</small></span><span><x-icon name="headset"/> Service client<br><small>À votre écoute</small></span></div></div><div class="hero-showcase">@if($featuredProduct)<a href="{{ route('products.show', $featuredProduct->slug) }}" class="hero-featured-product"><img src="{{ $featuredProduct->images->first() ? asset('storage/'.$featuredProduct->images->first()->path) : asset('images/logo.png') }}" alt="{{ $featuredProduct->name }}"><span>{{ $featuredProduct->name }}</span></a>@else<span class="hero-product-placeholder">Aucun produit disponible</span>@endif</div></section>

    <section id="categories" class="home-section category-section"><div class="section-heading"><div><span class="eyebrow">Explorez</span><h2>Nos catégories</h2><p>Trouvez facilement ce que vous cherchez</p></div><a href="{{ route('products.index') }}">Voir toutes les catégories <b>→</b></a></div><div class="category-grid">@forelse($categories->take(8) as $category)<a class="category-tile category-{{ $loop->iteration }}" href="{{ route('products.index', ['categorie' => $category->slug]) }}"><span class="category-art"><x-icon :name="['grid','bag','home','spark','bag','truck','spark','grid'][$loop->index]" size="24"/></span><strong>{{ $category->name }}</strong><small>{{ $category->products_count }} produits</small></a>@empty<p>Aucune catégorie disponible.</p>@endforelse</div></section>

    <section class="home-section"><div class="section-heading"><div><span class="eyebrow">Nos sélections</span><h2>Produits populaires</h2><p>Les produits actuellement disponibles</p></div><a href="{{ route('products.index') }}">Voir tous les produits <b>→</b></a></div><div class="home-products">@forelse($popularProducts as $product)<x-product-card :product="$product" />@empty<p>Aucun produit disponible pour l'instant.</p>@endforelse</div></section>

    <section class="promo-grid">@foreach($promoCategories->take(2) as $category)<a href="{{ route('products.index', ['categorie' => $category->slug]) }}" class="promo-panel promo-{{ $loop->first ? 'tech' : 'style' }}"><span>{{ $category->name }}</span><strong>{{ $loop->first ? 'La puissance entre vos mains' : 'Style pour tous les goûts' }}</strong><small>{{ $category->products_count }} produits disponibles dans cette catégorie.</small><b>Voir la collection&nbsp; →</b></a>@endforeach</section>

    <section id="about" class="why-section"><div class="section-heading centered"><div><h2>Pourquoi choisir HerveShop ?</h2><p>Votre satisfaction est notre priorité</p></div></div><div class="why-grid"><div><b><x-icon name="spark"/></b><strong>Produits de qualité</strong><small>Sélectionnés avec soin</small></div><div><b><x-icon name="truck"/></b><strong>Livraison rapide</strong><small>Partout au Togo</small></div><div><b><x-icon name="headset"/></b><strong>Service client</strong><small>À votre écoute</small></div><div><b><x-icon name="shield"/></b><strong>Paiement sécurisé</strong><small>Mobile Money & autres</small></div></div></section>

    <section class="home-section testimonials"><div class="section-heading centered"><div><span class="eyebrow">Ils nous font confiance</span><h2>Les avis de nos clients</h2><p>Découvrez leurs expériences</p></div></div><div class="testimonial-grid">@forelse($avis as $review)<article class="testimonial"><div class="testimonial-top"><span class="avatar">{{ strtoupper(substr($review->user?->name ?? 'C', 0, 1)) }}</span><strong>{{ $review->user?->name ?? 'Client' }}</strong></div><div class="stars">{{ str_repeat('★', $review->note) }}</div><p>“{{ $review->commentaire ?: 'Avis client validé.' }}”</p></article>@empty<p>Aucun avis client publié pour le moment.</p>@endforelse</div></section>

    <section class="newsletter"><div><strong><x-icon name="mail"/></strong><div><b>Restez informé de nos nouveautés !</b><small>Inscrivez-vous pour recevoir nos meilleures offres exclusives.</small></div></div><form><input type="email" placeholder="Votre adresse e-mail" aria-label="Votre adresse e-mail"><button type="button">S’inscrire&nbsp; →</button></form></section>
@endsection
