@extends('layouts.app')

@section('title', 'Catégories — HerveShop')
@section('meta_description', 'Explorez les catégories HerveShop et trouvez rapidement les produits qui vous correspondent.')
@section('canonical', route('categories.index'))

@section('content')
    <section class="category-hero"><div><span class="shop-kicker">Catégories</span><h1>Trouvez facilement<br><strong>ce que vous cherchez !</strong></h1><p>Explorez toutes nos catégories et découvrez une large gamme de produits de qualité, à des prix imbattables.</p></div><div class="category-hero-products">@foreach($categories->flatMap->products->take(4) as $product)<a href="{{ route('products.show', $product->slug) }}"><img src="{{ $product->images->first() ? asset('storage/'.$product->images->first()->path) : asset('images/logo.png') }}" alt="{{ $product->name }}"></a>@endforeach</div><div class="category-hero-promises"><span><x-icon name="truck"/> Livraison rapide<br><small>partout au Togo</small></span><span><x-icon name="shield"/> Paiement sécurisé<br><small>Mobile Money & autres</small></span><span><x-icon name="headset"/> Service client<br><small>disponible</small></span></div></section>

    <div class="category-page-layout"><aside class="shop-sidebar"><div class="shop-filter-title"><x-icon name="grid"/> <strong>Toutes les catégories</strong></div><div class="shop-category-list">@foreach($categories as $category)<a href="{{ route('products.index', ['categorie' => $category->slug]) }}"><span>{{ $category->name }}</span><small>{{ $category->products_count }}</small></a>@endforeach</div></aside><section class="category-results"><div class="section-heading"><div><h2>Nos catégories</h2><p>Des milliers de produits dans toutes vos catégories préférées.</p></div><a href="{{ route('products.index') }}">Voir tous les produits <b>→</b></a></div><div class="category-card-grid">@forelse($categories as $category)<a class="category-large-card category-large-{{ $loop->iteration }}" href="{{ route('products.index', ['categorie' => $category->slug]) }}"><div class="category-large-image">@if($category->products->first()?->images->first())<img src="{{ asset('storage/'.$category->products->first()->images->first()->path) }}" alt="{{ $category->name }}">@else<x-icon name="bag" size="48"/>@endif</div><div class="category-large-info"><span class="category-large-icon"><x-icon name="{{ ['grid','bag','home','spark','bag','truck','spark','grid'][$loop->index % 8] }}" size="17"/></span><strong>{{ $category->name }}</strong><small>{{ $category->products_count }} produits</small><b class="category-arrow">→</b></div></a>@empty<div class="card"><p>Aucune catégorie disponible.</p></div>@endforelse</div></section></div>

    <section class="category-benefits"><div><x-icon name="shield" size="27"/><strong>Pourquoi choisir HerveShop ?</strong><small>Votre satisfaction est notre priorité</small></div><div><x-icon name="truck"/><span>Livraison rapide<small>partout au Togo</small></span></div><div><x-icon name="shield"/><span>Paiement sécurisé<small>Mobile Money & autres</small></span></div><div><x-icon name="headset"/><span>Service client<small>disponible</small></span></div><a href="{{ route('products.index') }}" class="home-btn home-btn-primary">Découvrir la boutique&nbsp; →</a></section>
@endsection