@extends('layouts.app')

@section('title', 'À propos de HerveShop')
@section('meta_description', 'Découvrez HerveShop, une boutique en ligne togolaise pensée pour proposer des produits accessibles, une livraison simple et un service de confiance.')
@section('canonical', route('about.index'))

@section('content')
    <section class="about-hero"><div><span class="shop-kicker">À propos de HerveShop</span><h1>Plus qu’une boutique,<br><strong>une expérience de confiance !</strong></h1><p>HerveShop est votre boutique en ligne de référence au Togo et en Afrique de l’Ouest. Nous vous proposons des produits de qualité, sélectionnés pour répondre à vos besoins.</p><div class="hero-actions"><a href="{{ route('products.index') }}" class="home-btn home-btn-primary">Découvrir notre boutique&nbsp; →</a><a href="#contact" class="home-btn home-btn-light"><x-icon name="mail"/> Nous contacter</a></div></div><div class="about-hero-products">@forelse($showcaseProducts as $product)<a href="{{ route('products.show', $product->slug) }}"><img src="{{ $product->images->first() ? asset('storage/'.$product->images->first()->path) : asset('images/logo.png') }}" alt="{{ $product->name }}"></a>@empty<img src="{{ asset('images/logo.png') }}" alt="HerveShop">@endforelse</div><span class="about-script">Qualité<br><strong>Prix<br>Confiance</strong></span></section>

    <section class="about-story"><div class="about-story-image">@if($showcaseProducts->first()?->images->first())<img src="{{ asset('storage/'.$showcaseProducts->first()->images->first()->path) }}" alt="Produit HerveShop">@else<img src="{{ asset('images/logo.png') }}" alt="HerveShop">@endif</div><div class="about-story-copy"><span class="eyebrow">Notre histoire</span><h2>Comment tout a commencé ?</h2><p>HerveShop est née d’une idée simple : rendre les meilleurs produits accessibles à tous, facilement et en toute confiance.</p><p>Passionnés par la technologie et le commerce en ligne, nous construisons une expérience d’achat simple, rapide et sécurisée, avec un service client toujours à l’écoute.</p><strong>HerveShop</strong><small>Votre boutique de confiance</small></div><div class="about-values"><span class="eyebrow">Nos valeurs</span><h2>Ce qui nous guide chaque jour</h2><div class="values-grid"><div><b><x-icon name="shield"/></b><strong>Qualité</strong><small>Des produits sélectionnés avec soin.</small></div><div><b><x-icon name="spark"/></b><strong>Prix justes</strong><small>Le meilleur rapport qualité-prix.</small></div><div><b><x-icon name="truck"/></b><strong>Livraison rapide</strong><small>Partout au Togo et en Afrique de l’Ouest.</small></div><div><b><x-icon name="headset"/></b><strong>Service client</strong><small>À votre écoute, à chaque étape.</small></div></div></div></section>

    <section class="about-stats"><div><x-icon name="bag" size="28"/><strong>+{{ number_format($stats['products'], 0, ',', ' ') }}</strong><small>Produits disponibles</small></div><div><x-icon name="user" size="28"/><strong>+{{ number_format($stats['clients'], 0, ',', ' ') }}</strong><small>Clients inscrits</small></div><div><x-icon name="spark" size="28"/><strong>{{ $stats['rating'] }}/5</strong><small>Note moyenne</small></div><div><x-icon name="truck" size="28"/><strong>Partout</strong><small>au Togo et en Afrique de l’Ouest</small></div></section>

    <section class="about-cta" id="contact"><div><x-icon name="cart" size="32"/><div><strong>Rejoignez la famille HerveShop !</strong><small>Découvrez dès maintenant nos offres et profitez d’une expérience d’achat unique.</small></div></div><a href="{{ route('products.index') }}" class="home-btn home-btn-light">Voir la boutique&nbsp; →</a></section>
@endsection